#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Sep 18, 2024 05:17:04 PM EDT  platform: Linux
#    Sep 18, 2024 05:32:22 PM EDT  platform: Linux
#    Sep 20, 2024 12:19:46 PM EDT  platform: Linux
import sys
from tkinter import simpledialog, messagebox, filedialog
from tkinter.constants import *
from PIL import ImageTk
import pandas as pd

import RSS_GUI_layout
from IPfunctions import *
from LabelFusion import Fusion_TESD, Fusion_MV, Fusion_STAPLE, Fusion_MEAN
from seg_measures import *

_debug = True  # False to eliminate debug printing from callback functions.


def main(*args):
    '''Main entry point for the application.'''
    global root, rndSeed
    rndSeed = -1
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    print("Start-up!")
    # Creates a toplevel widget.
    global _top1, MainWindow, MaskFolder4Fusion
    _top1 = root
    MainWindow = RSS_GUI_layout.MainWin(_top1)
    MaskFolder4Fusion = "SynSegs/"

    ## init events

    MainWindow.Sigma_value = tk.StringVar()
    MainWindow.Sigma_entry.configure(textvariable=MainWindow.Sigma_value)

    MainWindow.LF_value = tk.StringVar()
    MainWindow.LF_entry.configure(textvariable=MainWindow.LF_value)

    MainWindow.HF_value = tk.StringVar()
    MainWindow.HF_entry.configure(textvariable=MainWindow.HF_value)

    MainWindow.ViewName = tk.StringVar()
    MainWindow.ViewName_label.configure(textvariable=MainWindow.ViewName)

    MainWindow.opt_var = tk.IntVar()
    MainWindow.Input_view_radiobutton.configure(variable=MainWindow.opt_var, value=1, command=choose_view)
    MainWindow.Syn_view_radiobutton.configure(variable=MainWindow.opt_var, value=2, command=choose_view)
    MainWindow.Overlay_view_radiobutton.configure(variable=MainWindow.opt_var, value=3, command=choose_view)

    MainWindow.SelectMode_value = tk.BooleanVar()
    MainWindow.SelectMode_TCheckbutton.configure(variable=MainWindow.SelectMode_value)

    MainWindow.Criterion_text = tk.StringVar()
    MainWindow.Criterion_TCombobox.configure(textvariable=MainWindow.Criterion_text)

    MainWindow.SelectFrom_value = tk.StringVar()
    MainWindow.SelectFrom_entry.configure(textvariable=MainWindow.SelectFrom_value)
    MainWindow.SelectTo_value = tk.StringVar()
    MainWindow.SelectTo_entry.configure(textvariable=MainWindow.SelectTo_value)

    ## set default values
    MainWindow.Sigma_value.set(1)
    MainWindow.LF_scale.configure(from_=0)
    MainWindow.LF_value.set(0)
    MainWindow.HF_scale.configure(from_=1)
    MainWindow.SelectMode_value.set(False)
    MainWindow.Criterion_text.set('DICE')
    MainWindow.SelectFrom_value.set(0.93)
    MainWindow.SelectTo_value.set(0.95)

    ## disable some functions
    MainWindow.Syn_view_radiobutton.configure(state="disabled")
    MainWindow.Overlay_view_radiobutton.configure(state="disabled")

    MainWindow.DispASynSeg_button.configure(state="disabled")
    MainWindow.SynSegPivot_button.configure(state="disabled")
    MainWindow.DispFusion_button.configure(state="disabled")

    ## set functions
    _top1.resizable(width=False, height=False)  # fixed window
    # trace value change events
    # MainWindow.HF_value.trace("w", lambda name, index, mode, var=MainWindow.HF_value: HF_value_change(var))
    # MainWindow.LF_value.trace("w", lambda name, index, mode, var=MainWindow.LF_value: LF_value_change(var))

    MainWindow.LF_entry.bind("<ButtonPress-1>", LF_entry_click)
    MainWindow.HF_entry.bind("<ButtonPress-1>", HF_entry_click)
    # MainWindow.DispFusion_button.bind("<ButtonRelease-1>", MainWindow.fusion_popup)
    # MainWindow.SynSegPivot_button.bind("<ButtonRelease-1>", MainWindow.pivot_popup)
    MainWindow.Main_img.bind("<ButtonPress-1>", Main_img_click)

    # user should load a mask file at the beginning
    LoadImg_click()

    root.mainloop()


def LF_entry_click(event):
    # print("clicked!")
    while True:
        USER_INP = simpledialog.askinteger(title="Value Input",
                                           prompt="Input the value for Low Frequency:",
                                           initialvalue=MainWindow.LF_value.get())
        if USER_INP != None:  # not a None
            if USER_INP < int(MainWindow.HF_value.get()):
                if USER_INP > -1:
                    MainWindow.LF_value.set(USER_INP)
                    refresh_scale()
                    break
                else:
                    messagebox.showinfo(title="Error",
                                        message="Low Frequency cannot be smaller than 0")

            else:
                messagebox.showinfo(title="Error",
                                    message="Low Frequency must be smaller than High Frequency: " + str(
                                        MainWindow.HF_value.get()))
        else:  # click "cancel"
            break


def HF_entry_click(event):
    # print("clicked!")
    while True:
        USER_INP = simpledialog.askinteger(title="Value Input",
                                           prompt="Input the value for High Frequency:",
                                           initialvalue=MainWindow.HF_value.get())
        if USER_INP != None:  # not a None
            if USER_INP > int(MainWindow.LF_value.get()):
                if USER_INP < Max_value + 1:
                    MainWindow.HF_value.set(USER_INP)
                    refresh_scale()
                    break
                else:
                    messagebox.showinfo(title="Error",
                                        message="High Frequency cannot be greater than " + str(Max_value))

            else:
                messagebox.showinfo(title="Error",
                                    message="High Frequency must be greater than Low Frequency: " + str(
                                        MainWindow.LF_value.get()))
        else:  # click "cancel"
            break


def Main_img_click(event):
    # print("Main_img clicked!")
    opt = MainWindow.opt_var.get()

    if opt == 1:
        img = Image.open("T_mask.png")

    elif opt == 2:
        img = Image.open("S_mask.png")

    elif opt == 3:
        img = Image.open("overlay_display.png")

    plt.imshow(img, cmap='gray')
    plt.show()


# def HF_value_change(HF_var):
#     MainWindow.HF_scale.set(HF_var.get())
#
# def LF_value_change(LF_var):
#     MainWindow.LF_scale.set(LF_var.get())

def refresh_scale():
    # set scales by new values from Entry
    MainWindow.LF_scale.set(MainWindow.LF_value.get())
    MainWindow.HF_scale.set(MainWindow.HF_value.get())


def refresh_display(opt):
    if opt == 1:
        img = Image.open("T_mask.png")
        resized_image = img.resize((300, 300), Image.ANTIALIAS)
        new_image = ImageTk.PhotoImage(resized_image)
        MainWindow.Main_img.create_image(0, 0, anchor=tk.NW, image=new_image)
        root.mainloop()
    elif opt == 2:
        img = Image.open("S_mask.png")
        resized_image = img.resize((300, 300), Image.ANTIALIAS)
        new_image = ImageTk.PhotoImage(resized_image)
        MainWindow.Main_img.create_image(0, 0, anchor=tk.NW, image=new_image)
        root.mainloop()
    elif opt == 3:
        img = Image.open("overlay_display.png")
        resized_image = img.resize((300, 300), Image.ANTIALIAS)
        new_image = ImageTk.PhotoImage(resized_image)
        MainWindow.Main_img.create_image(0, 0, anchor=tk.NW, image=new_image)
        root.mainloop()


def gen_synseg(num):
    # global rndSeed
    # if rndSeed!=-1:
    #     np.random.seed(rndSeed)
    # else:
    #     np.random.seed(None)

    for i in tqdm(range(1, num + 1)):  # gen num SynSegs
        try_times = 0
        while True:
            fd_code = bd2Fdesc(mask)
            CFcode = FD_change(fd_code,
                               l=int(MainWindow.LF_value.get()),
                               h=int(MainWindow.HF_value.get()),
                               sigma=float(MainWindow.Sigma_value.get()))

            re_img = Fdesc2bd(CFcode, mask.shape)
            syn_img, eligible = contour2mask(re_img)

            if eligible:
                cv2.imwrite("SynSegs/synseg_%d_.png" % i, syn_img * 255)

                # Enable display buttons after successful running
                MainWindow.DispASynSeg_button.configure(state="normal")
                MainWindow.SynSegPivot_button.configure(state="normal")
                MainWindow.DispFusion_button.configure(state="normal")
                MainWindow.DispFusion_button.bind("<ButtonRelease-1>", MainWindow.fusion_popup)
                MainWindow.SynSegPivot_button.bind("<ButtonRelease-1>", MainWindow.pivot_popup)

                break

            else:
                try_times += 1
                if try_times > 99:  # try 100 times
                    print("Task unsuccessful: cannot create an eligible mask for " + str(try_times)
                          + " times trying in a least one round, need to set different params.")
                    tk.messagebox.showwarning("Task unsuccessful",
                                              "Cannot create an eligible mask for " + str(try_times)
                                              + " times trying in a least one round, need to set different params.")
                    return

                # print("Cannot create an eligible mask, tried " + str(try_times)
                #       + "/100 times or stop to set different params.")


def gen_synseg_selet(num, metric_func, From, To):
    # global rndSeed
    # if rndSeed!=-1:
    #     np.random.seed(rndSeed)
    # else:
    #     np.random.seed(None)

    for i in tqdm(range(1, num + 1)):  # gen num SynSegs
        try_times_mask = 0
        try_times_selet = 0
        while True:
            fd_code = bd2Fdesc(mask)
            CFcode = FD_change(fd_code,
                               l=int(MainWindow.LF_value.get()),
                               h=int(MainWindow.HF_value.get()),
                               sigma=float(MainWindow.Sigma_value.get()))

            re_img = Fdesc2bd(CFcode, mask.shape)
            syn_img, eligible = contour2mask(re_img)

            if eligible:
                try_times_mask = 0
                # test for selection
                score = metric_func(mask, syn_img)

                if score > From and score < To:
                    cv2.imwrite("SynSegs/synseg_%d_.png" % i, syn_img * 255)

                    # Enable display buttons after successful running
                    MainWindow.DispASynSeg_button.configure(state="normal")
                    MainWindow.SynSegPivot_button.configure(state="normal")
                    MainWindow.DispFusion_button.configure(state="normal")
                    MainWindow.DispFusion_button.bind("<ButtonRelease-1>", MainWindow.fusion_popup)
                    MainWindow.SynSegPivot_button.bind("<ButtonRelease-1>", MainWindow.pivot_popup)

                    break

                else:  # try for selestion
                    try_times_selet += 1
                    if try_times_selet > 199:  # try 200 times
                        print("Segmentation selection unsuccessful: cannot create a required mask for " + str(
                            try_times_selet)
                              + " times trying in a least one round, need to set a different selection metric.")
                        tk.messagebox.showwarning("Segmentation selection unsuccessful",
                                                  "Cannot create a required mask for " + str(try_times_selet)
                                                  + " times trying in a least one round, need to set a different selection metric.")
                        return

                    print("The mask is not in the selection, tried " + str(try_times_selet) +
                          "/200 times or stop to set a different selection metric.", end="\r",
                          flush=True)

            else:  # try for eligible syn_mask
                try_times_mask += 1
                if try_times_mask > 99:  # try 100 times
                    print("Task unsuccessful: cannot create an eligible mask for " + str(try_times_mask)
                          + " times trying in a least one round, need to set different params.")
                    tk.messagebox.showwarning("Task unsuccessful",
                                              "Cannot create an eligible mask for " + str(try_times_mask)
                                              + " times trying in a least one round, need to set different params.")
                    return

                # print("Cannot create an eligible mask, tried " + str(try_times_mask)
                #       + "/100 times or stop to set different params.")


def sample_display(truth_file, seg_file):
    ## save seg to "S_mask.png",
    seg_img = cv2.imread(seg_file, cv2.IMREAD_GRAYSCALE)
    cv2.imwrite("S_mask.png", seg_img)

    ## save truth to "T_mask.png"
    truth_img = cv2.imread(truth_file, cv2.IMREAD_GRAYSCALE)
    cv2.imwrite("T_mask.png", truth_img)

    ## save "overlay_display.png"
    # Find contours
    contours, _ = cv2.findContours(seg_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    # Draw contours on a blank image
    contour_image = np.zeros_like(seg_img)
    cv2.drawContours(contour_image, contours, -1, (255, 255, 255), 1)
    k = 3
    overlay = (contour_image / 255) * k + (truth_img / 255)
    overlay[overlay == k + 1] = k
    plt.figure(frameon=False)
    plt.axis('off')
    plt.imshow(overlay, interpolation='none')
    plt.savefig("overlay_display.png", transparent=True, pad_inches=0, bbox_inches='tight')
    plt.close()

    ## display metrics btw seg_img and truth_img
    MainWindow.Metrics_listbox.delete(0, 99)  # refresh the list
    MainWindow.Metrics_listbox.insert(END, "Dice:" + str(round(DICE(truth_img, seg_img), 5)))
    MainWindow.Metrics_listbox.insert(END, "JAC:" + str(round(JAC(truth_img, seg_img), 5)))
    MainWindow.Metrics_listbox.insert(END, "HD:" + str(round(HD(truth_img, seg_img), 5)))
    MainWindow.Metrics_listbox.insert(END, "MSI:" + str(round(MSI(truth_img, seg_img), 5)))

    # Enable display buttons after successful running
    MainWindow.Syn_view_radiobutton.configure(state="normal")
    MainWindow.Overlay_view_radiobutton.configure(state="normal")

    ## display images
    refresh_display(MainWindow.opt_var.get())

    root.mainloop()


def Gen1_button_click(*args):
    fd_code = bd2Fdesc(mask)

    # global rndSeed
    # if rndSeed!=-1:
    #     np.random.seed(rndSeed)
    # else:
    #     np.random.seed(None)

    CFcode = FD_change(fd_code,
                       l=int(MainWindow.LF_value.get()),
                       h=int(MainWindow.HF_value.get()),
                       sigma=float(MainWindow.Sigma_value.get()))

    re_img = Fdesc2bd(CFcode, mask.shape)
    # cv2.imwrite("_temp.png", re_img * 255)
    syn_img, eligible = contour2mask(re_img)

    if not eligible:
        print("Cannot create an eligible mask, try again or set different params.")
        return

    # print(syn_img)
    # Converts bool to integer, which gives 0 for False and 1 for True, and multiplies it by 255 to make a (bit-)mask before writing it.
    cv2.imwrite("syn_mask.png", syn_img * 255)

    '''
    
    MainWindow.Metrics_listbox.delete(0,99)  # refresh the list
    MainWindow.Metrics_listbox.insert(END, "Dice:"+ str(round(DICE(mask,syn_img),5)))
    MainWindow.Metrics_listbox.insert(END, "JAC:" + str(round(JAC(mask, syn_img), 5)))
    MainWindow.Metrics_listbox.insert(END, "HD:" + str(round(HD(mask, syn_img), 5)))

    # print("Dice Coefficient: ", DICE(mask,syn_img))
    # print("Jaccard Coefficient: ", JAC(mask, syn_img))
    # print("Hausdorff Distance: ", HD(mask, syn_img))

    # bkgr=0, mask=1, reImg=k
    k=3
    overlay = re_img*k+mask
    overlay[overlay==k+1]=k

    plt.figure(frameon=False)
    # plt.imshow(syn_img, cmap='Greys_r', interpolation='none')
    plt.axis('off')
    plt.imshow(overlay, interpolation='none')
    # plt.imshow(syn_img + mask * 2, cmap='Greys_r', interpolation='none')

    plt.savefig("overlay_display.png", transparent=True, pad_inches=0, bbox_inches='tight')
    plt.close()
    # plt.show()

    img = Image.open("overlay_display.png")
    resized_image = img.resize((300,300), Image.ANTIALIAS)
    new_image = ImageTk.PhotoImage(resized_image)
    MainWindow.Main_img.create_image(0, 0, anchor=tk.NW, image=new_image)
    '''
    truth_file = "truth_mask.png"
    seg_file = "syn_mask.png"
    MainWindow.opt_var.set(3)
    MainWindow.ViewName.set("SynSeg 1/1")
    sample_display(truth_file, seg_file)

    root.mainloop()

    # print(MainWindow.Sigma_value.get())
    if _debug:
        print('RSS_GUI_main.Apply_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def GenN_button_click(*args):
    global rndSeed
    if rndSeed != -1:
        response = tk.messagebox.askyesno("Random seed = " + str(rndSeed),
                                          "\t\t\t\t\nA random seed is fixed; the sequence of random values will be fixed and depended on the seed until the seed reset or the program restarted." +
                                          "\t\t\t\t \nTo change or remove the random seed, click <Seed> button."
                                          "\t\t\t\t \nContinue? \t\t\t\t")
        if response == False:
            return

    if MainWindow.SelectMode_value.get():
        the_title = "Gen N **in Selection Mode**"
    else:
        the_title = "Gen N"

    while True:
        USER_INP = simpledialog.askinteger(title=the_title,
                                           prompt="Input the number of SynSegs for generation:",
                                           initialvalue=10)
        if USER_INP != None:  # not a None

            if USER_INP > 0:
                if not os.path.exists('SynSegs/'):
                    os.makedirs('SynSegs/')
                else:
                    shutil.rmtree('SynSegs/')
                    os.makedirs('SynSegs/')

                    if MainWindow.SelectMode_value.get():
                        # Gen N **in Selection Mode**

                        # Get the function object from globals() dictionary and call it
                        metric_func = globals()[MainWindow.Criterion_text.get()]
                        From = float(MainWindow.SelectFrom_value.get())
                        To = float(MainWindow.SelectTo_value.get())

                        gen_synseg_selet(USER_INP, metric_func, From, To)

                        if rndSeed != -1:
                            RndS = rndSeed
                        else:
                            RndS = 'N/A'
                        params = {
                            'Number': USER_INP,
                            'Sigma': float(MainWindow.Sigma_value.get()),
                            'Low frequency': int(MainWindow.LF_value.get()),
                            'High frequency': int(MainWindow.HF_value.get()),
                            'Random seed': RndS,
                            'Selection Model': 'ON',
                            'Selection Metric': MainWindow.Criterion_text.get(),
                            'Selection From': From,
                            'Selection To': To
                        }
                        save_log('GanN_params', params)

                    else:
                        gen_synseg(USER_INP)

                        if rndSeed != -1:
                            RndS = rndSeed
                        else:
                            RndS = 'N/A'
                        params = {
                            'Number': USER_INP,
                            'Sigma': float(MainWindow.Sigma_value.get()),
                            'Low frequency': int(MainWindow.LF_value.get()),
                            'High frequency': int(MainWindow.HF_value.get()),
                            'Random seed': RndS,
                            'Selection Model': 'OFF'
                        }
                        save_log('GanN_params', params)

                break
            else:
                messagebox.showinfo(title="Error",
                                    message="The number cannot be smaller than 1")

        else:  # click "cancel"
            break

    if _debug:
        print('RSS_GUI_main.GenN_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def LoadImg_click(*args):
    # Open a file dialog to select an image file
    filepath = filedialog.askopenfilename(title="Input a truth mask",
                                          filetypes=[("Image Files", "*.jpg *.png *.jpeg *.gif")])
    # print (filepath)
    if filepath:
        # if os.path.isfile("truth_mask.png"):  # previous truth mask exists
        #     print(f"Use the previous truth mask.")
        # else:
        try:
            # If a file is selected, copy and rename it
            shutil.copy(filepath, "truth_mask.png")
            print(f"Selected file loaded: {filepath}")

        except Exception as e:
            print(e)
            print(f"Use the previous truth mask.")

    else:
        # No file selected
        if os.path.isfile("truth_mask.png"):  # previous truth mask exists
            print(f"Use the previous truth mask.")
        else:  # copy and rename the default one
            shutil.copy("truth_mask_sample.png", "truth_mask.png")
            print(f"Loaded the default mask: truth_mask_sample.png")

    # Load the binary mask image
    # Load an image in the script
    img = cv2.imread("truth_mask.png", cv2.IMREAD_GRAYSCALE)
    # img = Image.open("truth_mask.png")

    ## set values for LF & HF
    global mask, Max_value
    mask = imbinarize(img)  # binarize area image
    fd_code = bd2Fdesc(mask)
    Len = fd_code.shape[0]
    print('Total FD# :', Len)

    Max_value = Len // 2

    MainWindow.LF_scale.configure(to=Max_value - 1)
    MainWindow.LF_value.set(2)

    MainWindow.HF_scale.configure(to=Max_value)
    MainWindow.HF_value.set(10)
    refresh_scale()

    # Resize the Image using resize method
    # resized_image = img.resize((300, 300), Image.ANTIALIAS)
    resized_image = cv2.resize(img, (300, 300))

    # Convert the Image object into a TkPhoto object
    new_image = ImageTk.PhotoImage(Image.fromarray(resized_image))
    # image_file = tk.PhotoImage(file='truth_mask.png')

    MainWindow.Main_img.create_image(0, 0, anchor=tk.NW, image=new_image)

    MainWindow.opt_var.set(1)
    root.mainloop()

    if _debug:
        print('RSS_GUI_main.LoadImg_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def HF_silde(*args):
    if int(MainWindow.HF_scale.get()) > int(MainWindow.LF_value.get()):
        MainWindow.HF_value.set(MainWindow.HF_scale.get())
    else:
        refresh_scale()

    if _debug:
        # print('RSS_GUI_main.HF_silde')
        # for arg in args:
        #     print ('    another arg:', arg)
        sys.stdout.flush()


def LF_silde(*args):
    if int(MainWindow.LF_scale.get()) < int(MainWindow.HF_value.get()):
        MainWindow.LF_value.set(MainWindow.LF_scale.get())
    else:
        refresh_scale()

    if _debug:
        # print('RSS_GUI_main.LF_silde')
        # for arg in args:
        #     print ('    another arg:', arg)
        sys.stdout.flush()


def DispFusion_button_click(*args):
    #  ref: MainWindow.DispFusion_button.bind in main()
    if _debug:
        print('RSS_GUI_main.DispFusion_button_click')
        for arg in args:
            print('	another arg:', arg)
        sys.stdout.flush()


def choose_view():
    refresh_display(MainWindow.opt_var.get())
    # selection = "You selected the option " + str(MainWindow.opt_var.get())
    # MainWindow.View_label.config(text=selection)


def DispASynSeg_button_click(*args):
    total_num = len(os.listdir('SynSegs/'))

    while True:
        USER_INP = simpledialog.askinteger(title="Choose a number in 1~" + str(total_num),
                                           prompt="Input a SynSeg number for display:",
                                           initialvalue=1)
        if USER_INP != None:  # not a None

            if (USER_INP >= 1) and (USER_INP <= total_num):

                truth_file = "truth_mask.png"
                seg_file = "SynSegs/synseg_" + str(USER_INP) + "_.png"
                MainWindow.opt_var.set(3)
                MainWindow.ViewName.set("SynSeg " + str(USER_INP) + "/" + str(total_num))
                sample_display(truth_file, seg_file)

                break
            else:
                messagebox.showinfo(title="Error",
                                    message="The SynSeg number must be in 1~" + str(total_num))

        else:  # click "cancel"
            break

    if _debug:
        print('RSS_GUI_main.DispASynSeg_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def SynSegPivot_button_click(*args):
    if _debug:
        print('RSS_GUI_support.SynSegPivot_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def plot_dice(*args):
    Plot_res(SegCompare_1vN("T_mask.png", "SynSegs/", DICE),
             'Dice-Sørensen coefficient')

    if _debug:
        print('RSS_GUI_main.plot_dice')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def plot_hd(*args):
    Plot_res(SegCompare_1vN("T_mask.png", "SynSegs/", HD),
             'Hausdorff distance')
    if _debug:
        print('RSS_GUI_main.plot_hd')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def plot_jac(*args):
    Plot_res(SegCompare_1vN("T_mask.png", "SynSegs/", JAC),
             'Jaccard index')
    if _debug:
        print('RSS_GUI_main.plot_jac')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def plot_msi(*args):
    Plot_res(SegCompare_1vN("T_mask.png", "SynSegs/", MSI),
             'Medical similarity index (MSI)')
    if _debug:
        print('RSS_GUI_main.plot_msi')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def show_res_seg(*args):
    Fusion_MEAN(MaskFolder=MaskFolder4Fusion)

    img = cv2.imread("FusedMask_MEAN.png", cv2.IMREAD_GRAYSCALE)
    plt.imshow(img, cmap='gray')
    plt.show()

    if _debug:
        print('RSS_GUI_main.show_res_seg')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def show_mv_seg(*args):
    Fusion_MV(MaskFolder=MaskFolder4Fusion)

    truth_file = "truth_mask.png"
    seg_file = "FusedMask_MV.png"
    MainWindow.opt_var.set(3)
    MainWindow.ViewName.set("MV-fused Seg")
    sample_display(truth_file, seg_file)

    if _debug:
        print('RSS_GUI_main.show_mv_seg')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def show_staple_seg(*args):
    Fusion_STAPLE(MaskFolder=MaskFolder4Fusion)

    truth_file = "truth_mask.png"
    seg_file = "FusedMask_STAPLE.png"
    MainWindow.opt_var.set(3)
    MainWindow.ViewName.set("STAPLE-fused Seg")
    sample_display(truth_file, seg_file)

    if _debug:
        print('RSS_GUI_main.show_staple_seg')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def show_tesd_seg(*args):
    Fusion_TESD(MaskFolder=MaskFolder4Fusion)

    truth_file = "truth_mask.png"
    seg_file = "FusedMask_TESD.png"
    MainWindow.opt_var.set(3)
    MainWindow.ViewName.set("TESD-fused Seg")
    sample_display(truth_file, seg_file)

    if _debug:
        print('RSS_GUI_main.show_tesd_seg')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def SelectMode_Click(*args):
    if MainWindow.SelectMode_value.get():
        print("SelectMode ON")
    else:
        print("SelectMode OFF")

    if _debug:
        # print('RSS_GUI_main.SelectMode_Click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


# Function to read configurations from a file
def load_config(file_path):
    config_dict = {}
    with open(file_path, 'r') as file:
        for line in file:
            item, value = line.strip().split('=')
            config_dict[item] = value
    return config_dict

def save_log(filename, parameters, run_report):
    from datetime import datetime
    df = pd.DataFrame(run_report)

    timestamp = datetime.now().strftime("%y%m%d-%H%M%S")
    # Example output: {filename}_250811-143045.txt
    filename = f"{filename}_{timestamp}.txt"
    print(filename)

    """Save parameters to a text file"""
    with open(filename, 'w') as file:
        for key, value in parameters.items():
            file.write(f"{key}: {value}\n")
        file.write("\n")
        file.write("Running report:\n")
        file.write(df.to_string(index=False))



def UserFusion_button_click(*args):
    # Load the config file
    batch_config = load_config("batch_processing_config.txt")
    folder_in = batch_config["UserFusion_folder_in"]
    folder_out = batch_config["UserFusion_folder_out"]

    # folder_in = "UserFusion_in/"
    # folder_out = "UserFusion_out/"

    response = tk.messagebox.askyesno("Batch Processing: User Fusion",
                                      "Masks in each sub-folder under the folder: " + folder_in
                                      + "\t\t\t\t \n will be fused by different truthing methods and saved in the folder: " + folder_out + ".\t\t\t\t \n Fused masks from the same sub-folder are in one folder. " +
                                      "\t\t\t\t \n To customize the input/output folders, please edit the <batch_processing_config.txt>. " +
                                      "\t\t\t\t \n Changes will be applied next time. Continue? \t\t\t\t")

    if response:
        # User selected Yes

        for folder_name in tqdm(os.listdir(folder_in)):
            folder_path = os.path.join(folder_in, folder_name)
            fused_folder_name = f"{folder_name}_fusion"
            fused_folder_path = os.path.join(folder_out, fused_folder_name)

            if not os.path.exists(fused_folder_path):
                os.makedirs(fused_folder_path)
            else:
                shutil.rmtree(fused_folder_path)
                os.makedirs(fused_folder_path)

            # print(fused_folder_path)

            Fusion_MV(MaskFolder=folder_path, output_folder=fused_folder_path)
            Fusion_STAPLE(MaskFolder=folder_path, output_folder=fused_folder_path)
            Fusion_TESD(MaskFolder=folder_path, output_folder=fused_folder_path)

    if _debug:
        print('RSS_GUI_main.UserFusion_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


# Function to save configurations to a file
# def save_config(file_path, config_dict):
#     with open(file_path, 'w') as file:
#         for item, value in config_dict.items():
#             file.write(f"{item}={value}\n")
def UserSyn_button_click(*args):
    global rndSeed
    if rndSeed != -1:
        answer = tk.messagebox.askyesno("Random seed = " + str(rndSeed),
                                        "\t\t\t\t\nA random seed is fixed; the sequence of random values will be fixed and depended on the seed until the seed reset or the program restarted." +
                                        "\t\t\t\t \nTo change or remove the random seed, click <Seed> button."
                                        "\t\t\t\t \nContinue? \t\t\t\t")
        if answer == False:
            return

    # Load the config file
    batch_config = load_config("batch_processing_config.txt")
    mask_folder = batch_config["UserSyn_mask_folder"]
    output_folder = batch_config["UserSyn_output_folder"]

    if MainWindow.SelectMode_value.get():
        the_title = "Batch Processing: User Synthesis **in Selection Mode**"
    else:
        the_title = "Batch Processing: User Synthesis"

    response = tk.messagebox.askyesno(the_title,
                                      "N (to be asked later) SynSegs will be generated from each original mask in the folder: " + mask_folder
                                      + "\t\t\t\t \n and saved in the folder: " + output_folder + ".\t\t\t\t \n SynSegs generated from the same original mask are in one folder. " +
                                      "\t\t\t\t \n To customize the input/output folders, please edit the <batch_processing_config.txt>. " +
                                      "\t\t\t\t \n Changes will be applied next time. Continue? \t\t\t\t")

    # mask_folder = "UserSyn_in/"
    # output_folder = "UserSyn_out/"

    # configurations = {"UserSyn_mask_folder": mask_folder,
    #                   "UserSyn_output_folder": output_folder}
    # file_path = "batch_processing_config.txt"
    # # Save to file
    # save_config(file_path, configurations)

    if MainWindow.SelectMode_value.get():
        the_title_N = "Gen N SynSegs from every user's masks **in Selection Mode**"
    else:
        the_title_N = "Gen N SynSegs from every user's masks"

    if response:
        # User selected Yes

        while True:
            USER_INP = simpledialog.askinteger(title=the_title_N,
                                               prompt="Input the number of SynSegs (N) for generation:\t\t\t\t\t\t",
                                               initialvalue=3)
            if USER_INP != None:  # not a None

                if USER_INP > 0:

                    if MainWindow.SelectMode_value.get():
                        # Gen N **in Selection Mode**

                        mask_augmentation_selet(mask_folder, output_folder, times=USER_INP,
                                                l=int(MainWindow.LF_value.get()),
                                                h=int(MainWindow.HF_value.get()),
                                                sigma=float(MainWindow.Sigma_value.get()),
                                                # Get the function object from globals() dictionary and call it
                                                metric_func=globals()[MainWindow.Criterion_text.get()],
                                                From=float(MainWindow.SelectFrom_value.get()),
                                                To=float(MainWindow.SelectTo_value.get()))
                        if rndSeed != -1:
                            RndS = rndSeed
                        else:
                            RndS = 'N/A'
                        params = {
                            'Number': USER_INP,
                            'Sigma': float(MainWindow.Sigma_value.get()),
                            'Low frequency': int(MainWindow.LF_value.get()),
                            'High frequency': int(MainWindow.HF_value.get()),
                            'Random seed': RndS,
                            'Selection Model': 'ON',
                            'Selection Metric': MainWindow.Criterion_text.get(),
                            'Selection From': MainWindow.SelectFrom_value.get(),
                            'Selection To': MainWindow.SelectTo_value.get()
                        }
                        save_log('UserSyn_params', params)

                        break

                    else:
                        run_report = mask_augmentation(mask_folder, output_folder, times=USER_INP,
                                          l=int(MainWindow.LF_value.get()),
                                          h=int(MainWindow.HF_value.get()),
                                          sigma=float(MainWindow.Sigma_value.get()))

                        if rndSeed != -1:
                            RndS = rndSeed
                        else:
                            RndS = 'N/A'
                        params = {
                            'Number': USER_INP,
                            'Sigma': float(MainWindow.Sigma_value.get()),
                            'Low frequency': int(MainWindow.LF_value.get()),
                            'High frequency': int(MainWindow.HF_value.get()),
                            'Random seed': RndS,
                            'Selection Model': 'OFF'
                        }
                        save_log('UserSyn_params', params, run_report)

                        break

                else:
                    messagebox.showinfo(title="Error",
                                        message="The number cannot be smaller than 1")

            else:  # click "cancel"
                break

    if _debug:
        print('RSS_GUI_main.UserSyn_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


def Seed_button_click(*args):
    global rndSeed
    # print("before: "+ str(rndSeed))

    while True:
        USER_INP = simpledialog.askinteger(title="Advanced function: set a random seed",
                                           prompt="A seed must be an integer between 0 and (2^32 - 1). Input -1 for removing the fixed random seed. \nIf you set a fixed random seed, the sequence of random values will be deterministic and dependent on the seed number.",
                                           initialvalue=rndSeed)
        if USER_INP != None:  # check if click cancel
            if USER_INP != -1:  # not a None
                if 0 <= USER_INP <= 2 ** 32 - 1:  # in correct range?
                    rndSeed = USER_INP
                    np.random.seed(rndSeed)

                    break
                else:
                    messagebox.showinfo(title="Error", message="Seed must be between 0 and (2^32 - 1).")
            else:
                rndSeed = -1  # None - keep None
                np.random.seed(None)
                print("No random seed set.")
                break
        else:  # click "cancel" - no change
            break

    # print("after: "+ str(rndSeed))

    if _debug:
        print('RSS_GUI_main.Seed_button_click')
        for arg in args:
            print('    another arg:', arg)
        sys.stdout.flush()


if __name__ == '__main__':
    RSS_GUI_layout.start_up()
